
name: AlmaLinux 9 CI

on:
  push:
    paths:
      - '.github/workflows/ci-alma9.yml'
      - '.github/workflows/reusable-ci.yml'
      - 'Dockerfile.alma9'
      - 'ansible/**'
      - 'initial_setup.sh'
      - 'update.sh'
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      distro: alma9
